class langue:
    def __init__(self):
        self.dict ={
            'oui':['yes'],'non':['no'],'Fermer':['Close'],
            'Nouveau':['New'],
            'Ouvrir':['Open'],
            'Enregistrer':['Save'],
            'Enregistrer sous':['Save as'],
            'Quitter':['Quit'],
            'Vitesses':['Velocities'],'Vitesse':['Velocity'],
            'Fichier':['File'],
            'Outils':['Tools'],
            'Aide':['Help'],
        # menus
            "Profil":['Profile'],
            "Pt observation":['Observation Pt'],
            "Import Donnees":['Import Data'],
            "graphe XY":['XY graph'],
            "Projet cree":['project created'],
            "Fichier iPHT3D importe":['iPHT3D file imported'],
            "Sauvegarde Reussie":['Successfull save'],
            "Sauvegarder":['Save'],
        # messages
            "Voulez-vous sauvegarder le projet?":['Do you want to save the project?'],
            "choisissez une variable":['Choose a variable'],
            "Import Donnees":['Import data'],
            "Variable importee":['Variable imported'],
            "Variable exporte":['Variable written'],
            "Vitesse exporte":['Velocities written'],
            "TraceurI exporte":['TracerI written'],
            "TraceurR exporte":['TracerR written'],
            "Reactions exportees":['Reactions written'],
            "Rt3d espece actuelle exportee":['Current Rt3d species written'],
            "click-droit pour arreter":['Right-click to stop'],
        # tip names (aide)
            "Choisir Carte":['Choose Map'],
            "Valeur de base":['Basis value'],
            "Choix du solveur":['Choose solver'],"Parametres":['Parameters'],
            "Lancer":['Run'],
            "Temps pour calcul":['Calcuation time steps'],
            "Import BDonnee":['Import DBase'],
            "Chimie":['Chemistry'],
            "Affiche zones":['Show zones'],
            "Ecrire fichiers":['Write files'],
            "Lancer Particules":['Run Particles'],
            "Affiche zones":['Show zones'],
        # top bar
            "Modifier":['Modify'],
            "modifier zone":['modify zone'],
            "Ajout point":['Add point'],"Ajout ligne":['Add line'],
            "Ajout rectangle":['Add rectangle'],"Ajout polygone":['Add polygon'],
            "Ajout polygone variable":['Add variable polygon'],
            "Changer milieux":['Change media'],
            "Zones transitoires":['Transient zones'],
            "Historique Zone":['Transient data'],
            "Deplacer zone":['Move zone'],
            "Modifier polygone":['modify polygon'],
            "Detruire zone":['Delete zone'],
            "Detruire toutes zones":['Delete all zone'],
            "Infos sur les zones":['zone infos'],
            "Nom":['Name'],
            "Valeur":['Value'],
        #groupes
            "Aquifere":['Aquifer'],
            "Ecoulement":['Flow'],
            "Modele":['Model'],
        # Model
            "Type de Modele":['Model type'],"nb Milieux":['nb Media'],
            "Domaine":['Domain'],"Unites":['Units'],
            "Temps":['Time'],"temps":['time'],
            "Grille":['Grid'],"Largeur Cell":['Cell width'],"Hauteur Cell":['Cell height'],
            "Grille variable":['variable grid'],
            "Nb couche/milieu":['Nb layers/media'],
            "Choisir une carte":['choose a map'],
            "Fichier iPht3d importe":['iPht3d file imported'],
        # aquifere
            "Choisissez les unites":['Choose units'],"an":['y'],"j":['d'],
            "Selection de la variable":['Select a variable'],
            "Mur":['Bottom'],"Toit":['Top'],"Potentiel":['Head'],
            "CelluleInactive":['InactiveCells'],"Permeabilite":['Permeability'],
            "Forages":['Wells'],"Source":['source'],"Porosite":['Porosity'],"Recharge":['Recharge'],
            "Riviere":['River'],"Drain":['Drain'],"Emmagasin.":['Storage'],
            "Valeur de base":['Baseline value'],
            "creer zone":['create a zone'],
            "Milieu Bas":['Lower media'],
            "Milieu Haut":['Upper media'],
            "Interpoler":['Interpolate'],
            "Modification d'une zone":['modify a zone'],
            "Valeur":['Value'],
            "Veuillez selectionner une variable":['Please select a variable'],
            "Veuillez selectionner une zone":['Please select a zone'],
            "Modele":['Model'],
            "Milieu":['Media'],
        #ecoulement
            "Parametres Ecoulement":['Flow parameters'],
            "Moyenne" :['Mean'],"libre":['free'],"confine":['confined'],
            "Charge":['Head '],
            "Solveur":['Solver'],
            "Veuillez sauver le projet avant le calcul":['create or save your project'],
            "creez ou sauvez votre projet":['create or save your project'],
            "Fichiers non ecrits":['Files not written'],
            "Lancer modflow":['Run Modflow'],
            "Particules":['Particles'],
            "Caracteres genants dans repertoire":['Bad strings in folder name'],
        # Transport
            "Fichier MT3D ecrits":['MT3D files written'],
            "pas de fichiers":['no file'],
        # Pht3d
            "Especes":['Species'],
            "Temps":['Time'],
            "Methode":['Method'],
            "Particules":['Particles'],
            "Solveur":['Solver'],
            "Ecrire fichiers":['Write files'],
            "Fichiers ecrits":['files written'],"Fichiers non ecrits":['files not written'],
            "Database importee":['Database imported'],
            "Double porosite":['Dual porosity'],
            "Chimie recharge":['Recharge chemistry'],
            "Chimie domaine immobile":['Immobile domain chemistry'],
            "fichier pht3d_datab.dat absent":['pht3d_datab.dat file lacking'],
            "importez la base de donnees":['import database first'],
            "Fichiers PHT3D ecrits":['Pht3d files written'],
        # Vue
            "VUE":['VIEW'],
            "Plan":['Plane'],"Couche":['Layer'],"Carte":['Map'],
            "Traceur":['Tracer'],
            "Choisir":['Choose'],
            "Valeur ponderee":['Weighted value'],
        # Dialogues
            'Type Aquifere':['Aquifer type'],
            'confine':['confined'],'non confine':['unconfined'],
            'degradation sur phase solide':['degradation on solid phase'],
            "Transitoire":['Transient'],
            "Axes memes echelle":['Same scale for axes']
            }
    def getMot(self,mot):
        if self.dict.has_key(mot) : return self.dict[mot][0]
        else : return mot
