groups={
'1.btn':['1.1','1.2','1.3','1.4','1.5','1.6','1.7','1.8','1.9','1.10','1.11','1.12','1.13','1.14','1.15','1.16','1.17','1.18','1.19','1.20'],
'2.adv':['2.1','2.2','2.3','2.4','2.5'],
'3.dsp':['3.1','3.2','3.3','3.4'],
'4.ssm':['4.1','4.2','4.3','4.4','4.5','4.6','4.7','4.8'],
'5.gcg':''
}
lines={
'1.1': {'comm':'Title','cond':'','kw':['title'],'detail':[],'type':''},
'1.2': {'comm':'','cond':'','kw':['NLAY','NROW','NCOL','NPER','NCOMP','MCOMP'],
        'detail':['Nb of layers','Nb of rows','Nb of columns','Nb of periods','Nb components','Nb mobile comp.'],
        'type':''},
'1.3': {'comm':'','cond':'','kw':['TUNIT','LUNIT','MUNIT'],
        'detail':[['time units','-','days','hour'],['Length unit','-','M','ft'],['Mass unit','-','kg','lb']],
        'type':''},
'1.4': {'comm':'','cond':'','kw':['TRNOP'],'detail':['flags (adv, disp, ssm , chem gcg)'],
        'type':'string'},
'1.5':{'comm':'type of layer','cond':'','kw':['LAYCON'],'detail':[],'type':'string'},
'1.6':{'comm':'Col width','cond':'','kw':['DELR(NCOL)'],'detail':[],'type':'vec'},
'1.7':{'comm':'Row height','cond':'','kw':['DELC(NROW)'],'detail':[],'type':'vec'},
'1.8':{'comm':'Top','cond':'','kw':['HTOP(NCOL,NROW)'],'detail':[],'type':'arr'},
'1.9':{'comm':'Thickness','cond':'','kw':['DZ(NLAY,NCOL,NROW)'],'detail':[],'type':'arr'},
'1.10':{'comm':'Porosity','cond':'','kw':['PRSTY(NLAY,NCOL,NROW)'],'detail':[],'type':'arr'},
'1.11':{'comm':'Boundary conditions','cond':'','kw':['ICBUND(NLAY,NCOL,NROW)'],'detail':[],'type':'arr'},
'1.12':{'comm':'Concentrations','cond':'','kw':['SCONC(NLAY,NCOL,NROW)'],'detail':[],'type':'xarr'},
'1.13':{'comm':'Inactive cells and min saturation','cond':'','kw':['CINACT','THKMIN'],
        'detail':['Value for conc inactive cells','Minimum saturation in a cell'],'type':''},
'1.14':{'comm':'Printing flags','cond':'','kw':['IFMTCN','IFMTNP','IFMTRF','IFMTDP','SAVUCN'],
        'detail':['Concentrations','nb particles','Retard','Dispersion','Save to UCN'],'type':''},
'1.15':{'comm':'Nb of printing times','cond':'','kw':['NPRS'],'detail':[''],'type':''},
'1.16':{'comm':'Print times','cond':'NPRS>0','kw':['TIMPRS(NPRS)'],'detail':[''],'type':'string'},
'1.17':{'comm':'Observation points','cond':'','kw':['NOBS','NPROBS'],
        'detail':['Nb of observation points','Freq of printing'],'type':''},
'1.18':{'comm':'Obs points cells','cond':'NOBS>0','kw':['KOBS','IOBS','JOBS'],'detail':[''],'type':'nvec'},
'1.19':{'comm':'mass printing','cond':'','kw':['CHKMAS','NPRMAS'],'detail':[''],'type':''},
'1.20':{'comm':'Periods','cond':'','kw':['PERLEN(NPER)','NSTP(NPER)','TSMULT(NPER)','DT0(NPER)','MXSTRN(NPER)','TTSMULT(NPER)','TTSMAX(NPER)'],
        'detail':['Period length','nb of time steps','multiplying factor','start time','max T step in F steps','2nd multipl','2nd max tstep'],
        'type':'nvec2'},

'2.1': {'comm':'Major data','cond':'','kw':['MIXELM','PERCEL','MXPART','NADVFD'],
        'detail':['Method','Courant nb','Maximum nb particles','weighing scheme'],'type':''},
'2.2': {'comm':'Particles','cond':'','kw':['ITRACK','WD'],'detail':['Type of tracking','weighing factor'],'type':''},
'2.3': {'comm':'Particles details','cond':'MIXELM in [1,3]','kw':['DCEPS','NPLANE','NPL','NPH','NPMIN','NPMAX'],
        'detail':['minimum gradient','initial placement','initial number 1','initial number 2','min nb allowed','max nb allowed'],
        'type':''},
'2.4': {'comm':'Particles details','cond':'MIXELM in [2,3]','kw':['INTERP','NLSINK','NPSINK'],
        'detail':['Interpol scheme','Flag inital sink part','Nb inital sink part'],'type':''},
'2.5':{'comm':'Gradient to choose MOC scheme','cond':'MIXELM==3','kw':['DCHMOC'],'detail':[],'type':''},

'3.1':{'comm':'Longitudinal disp','cond':'','kw':['AL(NLAY)'],'detail':[],'type':'arr'},
'3.2':{'comm':'Ratio Transv/Horiz disp','cond':'','kw':['TRPT'],'detail':[],'type':'vec'},
'3.3':{'comm':'Ratio Vert/Horiz disp','cond':'','kw':['TRPV'],'detail':[],'type':'vec'},
'3.4':{'comm':'Diffusion coeff','cond':'','kw':['DMCOEF'],'detail':[],'type':'string'},

'4.1':{'comm':'Flags for active processes','cond':'','kw':['FWEL','FDRN','FRCH','FEVT','FRIV','FGHB'],
       'detail':[],'type':''},
'4.2':{'comm':'Max nb of sink/source','cond':'','kw':['MXSS'],'detail':[],'type':''},
'4.3':{'comm':'Recharge present?','cond':'FRCH==\'T\'','kw':['INCRCH'],'detail':[],'type':''},
'4.4':{'comm':'Recharge conc','cond':'FRCH==\'T\'','kw':['CRCH(NCOL,NROW)'],'detail':[],'type':'parr'},
'4.5':{'comm':'Evapotr present?','cond':'FEVT==\'T\'','kw':['INCEVT'],'detail':[],'type':''},
'4.6':{'comm':'Evapotr conc','cond':'FEVT==\'T\'','kw':['CEVT(NCOL,NROW)'],'detail':[],'type':'parr'},
'4.7':{'comm':'Nb of sink/source','cond':'','kw':['NSS'],'detail':[],'type':''},
'4.8':{'comm':'sink/source coords and type','cond':'','kw':['KSS','ISS','JSS','CSS','ITYPE','CSSMS(NCOMP)'],
       'detail':[],'type':'npoints'},
}